name: macOS unit tests

on:
  pull_request:
    paths:
      - "src/**"

jobs:
  build-bigsur:
    runs-on: macos-11
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
      - name: Install cmocka and lcov
        run: |
          brew install cmocka lcov
      - name: Build wazuh agent for macOS 11 with tests flags
        run: |
          make deps -C src TARGET=agent -j3
          LIBRARY_PATH=/usr/local/lib make -C src TARGET=agent -j3 DEBUG=1 TEST=1
      - name: Run wazuh unit tests for macOS 11
        run: |
          cd src/data_provider/build
          ctest -V
          cd ../../shared_modules/dbsync/build
          ctest -V
          cd ../../rsync/build
          ctest -V
          cd ../../../wazuh_modules/syscollector/build
          ctest -V
  build-monterey:
    runs-on: macos-12
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
      - name: Install cmocka and lcov
        run: |
          brew install cmocka lcov
      - name: Build wazuh agent for macOS 12 with tests flags
        run: |
          make deps -C src TARGET=agent -j3
          LIBRARY_PATH=/usr/local/lib make -C src TARGET=agent -j3 DEBUG=1 TEST=1
      - name: Run wazuh unit tests for macOS 12
        run: |
          cd src/data_provider/build
          ctest -V
          cd ../../shared_modules/dbsync/build
          ctest -V
          cd ../../rsync/build
          ctest -V
          cd ../../../wazuh_modules/syscollector/build
          ctest -V
  build-ventura:
    runs-on: macos-13
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
      - name: Install cmocka and lcov
        run: |
          brew install cmocka lcov
      - name: Build wazuh agent for macOS 13 with tests flags
        run: |
          make deps -C src TARGET=agent -j3
          LIBRARY_PATH=/usr/local/lib make -C src TARGET=agent -j3 DEBUG=1 TEST=1
      - name: Run wazuh unit tests for macOS 13
        run: |
          cd src/data_provider/build
          ctest -V
          cd ../../shared_modules/dbsync/build
          ctest -V
          cd ../../rsync/build
          ctest -V
          cd ../../../wazuh_modules/syscollector/build
          ctest -V
