name: macOS compilation test

on:
  pull_request:
    paths:
      - "src/**"

jobs:
  build-bigsur:
    runs-on: macos-11
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
      - name: Build wazuh agent for macOS 11
        run: |
          make deps -C src TARGET=agent -j2
          make -C src TARGET=agent -j2
  build-monterey:
    runs-on: macos-12
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
      - name: Build wazuh agent for macOS 12
        run: |
          make deps -C src TARGET=agent -j2
          make -C src TARGET=agent -j2
  build-ventura:
    runs-on: macos-13
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
      - name: Build wazuh agent for macOS 13
        run: |
          make deps -C src TARGET=agent -j2
          make -C src TARGET=agent -j2
